=== Rao00/Rao00-Mi-Viaje/Lenguaje de marcas/XML Evaluable/Ejercicio Final/EjercicioFinalValidation.dtd
<!ELEMENT situaciones (situacion+)>
<!ELEMENT situacion (id, nombre, tiempo-ejecucion, ejemplo, patrones)>
<!ATTLIST situacion tipo CDATA #REQUIRED>
<!ATTLIST situacion complejidad CDATA #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tiempo-ejecucion (#PCDATA)>
<!ELEMENT ejemplo (#PCDATA)>
<!ELEMENT patrones (patron+)>
<!ELEMENT patron (id-patron, resultado, operacion)>
<!ELEMENT id-patron (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT operacion (paso+)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST paso num CDATA #REQUIRED>

=== Rao00/Rao00-Mi-Viaje/1º DAW/Lenguaje de marcas/XML Evaluable/Ejercicio Final/EjercicioFinal.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="style.xsl" type="text/xsl"?>
<!DOCTYPE situaciones SYSTEM "EjercicioFinalValidation.dtd">
<situaciones>
  <situacion tipo="calculo" complejidad="simple">
    <id>c-s-1</id>
    <nombre>Suma</nombre>
    <tiempo-ejecucion>0.02ms</tiempo-ejecucion>
    <ejemplo>x + y = z</ejemplo>
    <patrones>
      <patron>
        <id-patron>c-s-1-1</id-patron>
        <resultado>x</resultado>
        <operacion>
          <paso num="1">y = y * -1</paso>
          <paso num="2">x = z - y</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-s-1-2</id-patron>
        <resultado>y</resultado>
        <operacion>
          <paso num="1">x = x * -1</paso>
          <paso num="2">y = z - x</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-s-1-3</id-patron>
        <resultado>z</resultado>
        <operacion>
          <paso num="1">x + y = z</paso>
        </operacion>
      </patron>
    </patrones>
  </situacion>
  <situacion tipo="calculo" complejidad="simple">
    <id>c-s-2</id>
    <nombre>Resta</nombre>
    <tiempo-ejecucion>0.03ms</tiempo-ejecucion>
    <ejemplo>x - y = z</ejemplo>
    <patrones>
      <patron>
        <id-patron>c-s-2-1</id-patron>
        <resultado>x</resultado>
        <operacion>
          <paso num="1">y = y * -1</paso>
          <paso num="2">x = z + y</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-s-2-2</id-patron>
        <resultado>y</resultado>
        <operacion>
          <paso num="1">x = x * -1</paso>
          <paso num="2">y = z - x</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-s-2-3</id-patron>
        <resultado>z</resultado>
        <operacion>
          <paso num="1">x - y = z</paso>
        </operacion>
      </patron>
    </patrones>
  </situacion>
  <situacion tipo="calculo" complejidad="media">
    <id>c-m-1</id>
    <nombre>Potencia</nombre>
    <tiempo-ejecucion>0.08ms</tiempo-ejecucion>
    <ejemplo>x ^ y = z</ejemplo>
    <patrones>
      <patron>
        <id-patron>c-m-1-1</id-patron>
        <resultado>x</resultado>
        <operacion>
          <paso num="1">x = y^√ z</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-m-1-2</id-patron>
        <resultado>y</resultado>
        <operacion>
          <paso num="1">logn(x ^ y) = logn(z)</paso>
          <paso num="2">y * logn(x) = logn(z)</paso>
          <paso num="3">y = logn(z) / logn(x)</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-m-1-3</id-patron>
        <resultado>z</resultado>
        <operacion>
          <paso num="1">x ^ y = z</paso>
        </operacion>
      </patron>
    </patrones>
  </situacion>
  <situacion tipo="calculo" complejidad="media">
    <id>c-m-2</id>
    <nombre>Raiz</nombre>
    <tiempo-ejecucion>0.21ms</tiempo-ejecucion>
    <ejemplo>sqrt[y](x) = z</ejemplo>
    <patrones>
      <patron>
        <id-patron>c-m-2-1</id-patron>
        <resultado>x</resultado>
        <operacion>
          <paso num="1">(sqrt[y](x))^y = (z)^y</paso>
          <paso num="2">x = z^y</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-s-2-2</id-patron>
        <resultado>y</resultado>
        <operacion>
          <paso num="1">x^1/y = z</paso>
          <paso num="2">(x^1/y)^y = (z)^y</paso>
          <paso num="3">x = z^y</paso>
          <paso num="4">logn(x) = y * logn(z)</paso>
          <paso num="5">logn(x) / logn(z) = y</paso>
        </operacion>
      </patron>
      <patron>
        <id-patron>c-s-2-3</id-patron>
        <resultado>z</resultado>
        <operacion>
          <paso num="1">sqrt[y](x) = z</paso>
        </operacion>
      </patron>
    </patrones>
  </situacion>
</situaciones>
